import type { Station, Train } from "./types";

export const MOCK_TRAINS: Train[] = [
  // 1. Western Line - FAST LOCAL (Sequence Verified)
  {
    id: "WR-F-01",
    name: "Churchgate Fast",
    from: "Virar",
    to: "Churchgate",
    schedule: [
      {
        id: "VR",
        name: "Virar",
        arrivalTime: "08:00",
        latitude: 19.4629,
        longitude: 72.8055,
      },
      {
        id: "BSR",
        name: "Vasai Road",
        arrivalTime: "08:10",
        latitude: 19.3852,
        longitude: 72.8345,
      },
      {
        id: "BVI",
        name: "Borivali",
        arrivalTime: "08:25",
        latitude: 19.229,
        longitude: 72.8598,
      },
      {
        id: "ADH",
        name: "Andheri",
        arrivalTime: "08:38",
        latitude: 19.1197,
        longitude: 72.8465,
      },
      {
        id: "BA",
        name: "Bandra",
        arrivalTime: "08:48",
        latitude: 19.0583,
        longitude: 72.8406,
      },
      {
        id: "DDR",
        name: "Dadar",
        arrivalTime: "08:55",
        latitude: 19.0183,
        longitude: 72.8427,
      },
      {
        id: "CCG",
        name: "Churchgate",
        arrivalTime: "09:10",
        latitude: 18.9348,
        longitude: 72.8277,
      },
    ],
  },

  // 2. Western Line - SLOW LOCAL (Sequence Verified)
  {
    id: "WR-S-01",
    name: "Churchgate Slow",
    from: "Borivali",
    to: "Churchgate",
    schedule: [
      {
        id: "BVI",
        name: "Borivali",
        arrivalTime: "07:31",
        latitude: 19.2291,
        longitude: 72.8574,
      },
      {
        id: "KDN",
        name: "Kandivali",
        arrivalTime: "07:35",
        latitude: 19.2042,
        longitude: 72.8517,
      },
      {
        id: "MDD",
        name: "Malad",
        arrivalTime: "07:38",
        latitude: 19.1873,
        longitude: 72.8488,
      },
      {
        id: "GMN",
        name: "Goregaon",
        arrivalTime: "07:42",
        latitude: 19.1645,
        longitude: 72.8485,
      },
      {
        id: "RMR",
        name: "Ram Mandir",
        arrivalTime: "07:45",
        latitude: 19.1494,
        longitude: 72.8505,
      },
      {
        id: "JOS",
        name: "Jogeshwari",
        arrivalTime: "07:49",
        latitude: 19.1352,
        longitude: 72.8485,
      },
      {
        id: "ADH",
        name: "Andheri",
        arrivalTime: "07:54",
        latitude: 19.1197,
        longitude: 72.8465,
      },
      {
        id: "VLP",
        name: "Vile Parle",
        arrivalTime: "07:58",
        latitude: 19.1005,
        longitude: 72.8441,
      },
      {
        id: "STC",
        name: "Santacruz",
        arrivalTime: "08:01",
        latitude: 19.079,
        longitude: 72.8412,
      },
      {
        id: "KHAR",
        name: "Khar Road",
        arrivalTime: "08:04",
        latitude: 19.0696,
        longitude: 72.8402,
      },
      {
        id: "BA",
        name: "Bandra",
        arrivalTime: "08:07",
        latitude: 19.0548,
        longitude: 72.8407,
      },
      {
        id: "MM",
        name: "Mahim",
        arrivalTime: "08:09",
        latitude: 19.0402,
        longitude: 72.8468,
      },
      {
        id: "MRU",
        name: "Matunga Road",
        arrivalTime: "08:13",
        latitude: 19.0277,
        longitude: 72.8466,
      },
      {
        id: "DDR",
        name: "Dadar",
        arrivalTime: "08:15",
        latitude: 19.0183,
        longitude: 72.8427,
      },
      {
        id: "PR",
        name: "Prabhadevi",
        arrivalTime: "08:18",
        latitude: 19.0075,
        longitude: 72.836,
      },
      {
        id: "LPR",
        name: "Lower Parel",
        arrivalTime: "08:21",
        latitude: 18.9964,
        longitude: 72.8308,
      },
      {
        id: "MX",
        name: "Mahalaxmi",
        arrivalTime: "08:24",
        latitude: 18.9818,
        longitude: 72.8242,
      },
      {
        id: "GTR",
        name: "Grant Road",
        arrivalTime: "08:28",
        latitude: 18.9633,
        longitude: 72.8163,
      },
      {
        id: "CYR",
        name: "Charni Road",
        arrivalTime: "08:31",
        latitude: 18.9504,
        longitude: 72.8186,
      },
      {
        id: "MEL",
        name: "Marine Lines",
        arrivalTime: "08:33",
        latitude: 18.946,
        longitude: 72.8235,
      },
      {
        id: "CCG",
        name: "Churchgate",
        arrivalTime: "08:36",
        latitude: 18.9348,
        longitude: 72.8277,
      },
    ],
  },

  // 3. Central Line - SLOW LOCAL (NEW ADDITION)
  {
    id: "CR-S-01",
    name: "Kalyan Slow",
    from: "CSMT",
    to: "Kalyan",
    schedule: [
      {
        id: "CSMT",
        name: "CSMT",
        arrivalTime: "09:00",
        latitude: 18.9404,
        longitude: 72.8355,
      },
      {
        id: "MSD",
        name: "Masjid",
        arrivalTime: "09:03",
        latitude: 18.9501,
        longitude: 72.8378,
      },
      {
        id: "SND",
        name: "Sandhurst Road",
        arrivalTime: "09:05",
        latitude: 18.9567,
        longitude: 72.8398,
      },
      {
        id: "BY",
        name: "Byculla",
        arrivalTime: "09:09",
        latitude: 18.9739,
        longitude: 72.8349,
      },
      {
        id: "CHG",
        name: "Chinchpokli",
        arrivalTime: "09:11",
        latitude: 18.9803,
        longitude: 72.835,
      },
      {
        id: "CRD",
        name: "Currey Road",
        arrivalTime: "09:13",
        latitude: 18.9868,
        longitude: 72.8364,
      },
      {
        id: "PR",
        name: "Parel",
        arrivalTime: "09:16",
        latitude: 18.995,
        longitude: 72.8413,
      },
      {
        id: "DR",
        name: "Dadar",
        arrivalTime: "09:19",
        latitude: 19.0202,
        longitude: 72.8441,
      },
      {
        id: "MTN",
        name: "Matunga",
        arrivalTime: "09:22",
        latitude: 19.028,
        longitude: 72.8553,
      },
      {
        id: "SIN",
        name: "Sion",
        arrivalTime: "09:25",
        latitude: 19.0435,
        longitude: 72.8624,
      },
      {
        id: "CLA",
        name: "Kurla",
        arrivalTime: "09:30",
        latitude: 19.0632,
        longitude: 72.8863,
      },
      {
        id: "VVH",
        name: "Vidyavihar",
        arrivalTime: "09:33",
        latitude: 19.0799,
        longitude: 72.895,
      },
      {
        id: "GC",
        name: "Ghatkopar",
        arrivalTime: "09:36",
        latitude: 19.0851,
        longitude: 72.9038,
      },
      {
        id: "VK",
        name: "Vikhroli",
        arrivalTime: "09:40",
        latitude: 19.1128,
        longitude: 72.92,
      },
      {
        id: "KJRD",
        name: "Kanjurmarg",
        arrivalTime: "09:43",
        latitude: 19.1306,
        longitude: 72.9248,
      },
      {
        id: "BND",
        name: "Bhandup",
        arrivalTime: "09:46",
        latitude: 19.1449,
        longitude: 72.9328,
      },
      {
        id: "NHU",
        name: "Nahur",
        arrivalTime: "09:49",
        latitude: 19.155,
        longitude: 72.9392,
      },
      {
        id: "MLD",
        name: "Mulund",
        arrivalTime: "09:52",
        latitude: 19.1711,
        longitude: 72.949,
      },
      {
        id: "TNA",
        name: "Thane",
        arrivalTime: "09:56",
        latitude: 19.1865,
        longitude: 72.976,
      },
      {
        id: "KLVA",
        name: "Kalva",
        arrivalTime: "10:01",
        latitude: 19.191,
        longitude: 72.9926,
      },
      {
        id: "MBQ",
        name: "Mumbra",
        arrivalTime: "10:06",
        latitude: 19.177,
        longitude: 73.0235,
      },
      {
        id: "DIVA",
        name: "Diva",
        arrivalTime: "10:09",
        latitude: 19.1865,
        longitude: 73.045,
      },
      {
        id: "KOPR",
        name: "Kopar",
        arrivalTime: "10:14",
        latitude: 19.213,
        longitude: 73.069,
      },
      {
        id: "DOM",
        name: "Dombivli",
        arrivalTime: "10:16",
        latitude: 19.2183,
        longitude: 73.0869,
      },
      {
        id: "THK",
        name: "Thakurli",
        arrivalTime: "10:19",
        latitude: 19.228,
        longitude: 73.098,
      },
      {
        id: "KYN",
        name: "Kalyan",
        arrivalTime: "10:24",
        latitude: 19.243,
        longitude: 73.132,
      },
    ],
  },

  // 4. Harbour Line - Goregaon to CSMT (NEW ADDITION)
  {
    id: "HR-S-02",
    name: "Goregaon Slow",
    from: "Goregaon",
    to: "CSMT",
    schedule: [
      {
        id: "GMN",
        name: "Goregaon",
        arrivalTime: "11:00",
        latitude: 19.1645,
        longitude: 72.8485,
      },
      {
        id: "RMR",
        name: "Ram Mandir",
        arrivalTime: "11:03",
        latitude: 19.15,
        longitude: 72.846,
      },
      {
        id: "JOS",
        name: "Jogeshwari",
        arrivalTime: "11:07",
        latitude: 19.1352,
        longitude: 72.8485,
      },
      {
        id: "ADH",
        name: "Andheri",
        arrivalTime: "11:12",
        latitude: 19.1197,
        longitude: 72.8465,
      },
      {
        id: "VLP",
        name: "Vile Parle",
        arrivalTime: "11:16",
        latitude: 19.099,
        longitude: 72.8481,
      },
      {
        id: "STC",
        name: "Santacruz",
        arrivalTime: "11:19",
        latitude: 19.081,
        longitude: 72.8447,
      },
      {
        id: "KHAR",
        name: "Khar Road",
        arrivalTime: "11:22",
        latitude: 19.0682,
        longitude: 72.8415,
      },
      {
        id: "BA",
        name: "Bandra",
        arrivalTime: "11:25",
        latitude: 19.0583,
        longitude: 72.8406,
      },
      {
        id: "KCE",
        name: "King's Circle",
        arrivalTime: "11:32",
        latitude: 19.0305,
        longitude: 72.858,
      },
      {
        id: "VDL",
        name: "Wadala Road",
        arrivalTime: "11:37",
        latitude: 19.021,
        longitude: 72.859,
      },
      {
        id: "SVE",
        name: "Sewri",
        arrivalTime: "11:41",
        latitude: 19.001,
        longitude: 72.849,
      },
      {
        id: "CTGN",
        name: "Cotton Green",
        arrivalTime: "11:44",
        latitude: 18.989,
        longitude: 72.843,
      },
      {
        id: "RRD",
        name: "Reay Road",
        arrivalTime: "11:46",
        latitude: 18.979,
        longitude: 72.841,
      },
      {
        id: "DKRD",
        name: "Dockyard Road",
        arrivalTime: "11:48",
        latitude: 18.968,
        longitude: 72.84,
      },
      {
        id: "SND",
        name: "Sandhurst Road",
        arrivalTime: "11:51",
        latitude: 18.9567,
        longitude: 72.8398,
      },
      {
        id: "MSD",
        name: "Masjid",
        arrivalTime: "11:54",
        latitude: 18.9501,
        longitude: 72.8378,
      },
      {
        id: "CSMT",
        name: "CSMT",
        arrivalTime: "11:57",
        latitude: 18.9404,
        longitude: 72.8355,
      },
    ],
  },

  // 5. Trans-Harbour Line - Thane to Panvel (Sequence Verified)
  {
    id: "TH-S-01",
    name: "Panvel Slow",
    from: "Thane",
    to: "Panvel",
    schedule: [
      {
        id: "TNA",
        name: "Thane",
        arrivalTime: "10:00",
        latitude: 19.1865,
        longitude: 72.976,
      },
      {
        id: "DIGH",
        name: "Digha Gaon",
        arrivalTime: "10:06",
        latitude: 19.1438,
        longitude: 72.9965,
      },
      {
        id: "ARLI",
        name: "Airoli",
        arrivalTime: "10:09",
        latitude: 19.1481,
        longitude: 73.004,
      },
      {
        id: "RBLE",
        name: "Rabale",
        arrivalTime: "10:12",
        latitude: 19.1306,
        longitude: 73.0115,
      },
      {
        id: "GNSL",
        name: "Ghansoli",
        arrivalTime: "10:15",
        latitude: 19.1118,
        longitude: 73.018,
      },
      {
        id: "KPHN",
        name: "Kopar Khairane",
        arrivalTime: "10:19",
        latitude: 19.0898,
        longitude: 73.019,
      },
      {
        id: "TRBE",
        name: "Turbhe",
        arrivalTime: "10:23",
        latitude: 19.073,
        longitude: 73.0185,
      },
      {
        id: "SNPD",
        name: "Sanpada",
        arrivalTime: "10:27",
        latitude: 19.065,
        longitude: 72.997,
      },
      {
        id: "VSH",
        name: "Vashi",
        arrivalTime: "10:30",
        latitude: 19.0755,
        longitude: 72.994,
      },
      {
        id: "NEU",
        name: "Nerul",
        arrivalTime: "10:38",
        latitude: 19.0345,
        longitude: 73.0185,
      },
      {
        id: "SWDV",
        name: "Seawoods",
        arrivalTime: "10:41",
        latitude: 19.0345,
        longitude: 73.0185,
      },
      {
        id: "BEPR",
        name: "Belapur CBD",
        arrivalTime: "10:44",
        latitude: 19.021,
        longitude: 73.0375,
      },
      {
        id: "KHAG",
        name: "Kharghar",
        arrivalTime: "10:48",
        latitude: 19.0435,
        longitude: 73.056,
      },
      {
        id: "MANR",
        name: "Mansarovar",
        arrivalTime: "10:51",
        latitude: 19.0206,
        longitude: 73.0658,
      },
      {
        id: "KNDS",
        name: "Khandeshwar",
        arrivalTime: "10:54",
        latitude: 19.0065,
        longitude: 73.085,
      },
      {
        id: "PNVL",
        name: "Panvel",
        arrivalTime: "10:59",
        latitude: 18.99,
        longitude: 73.1185,
      },
    ],
  },

  // 6. Uran Line - Nerul to Uran (NEW ADDITION)
  {
    id: "UL-S-01",
    name: "Uran Slow",
    from: "Nerul",
    to: "Uran",
    schedule: [
      {
        id: "NEU",
        name: "Nerul",
        arrivalTime: "12:00",
        latitude: 19.0345,
        longitude: 73.0185,
      },
      {
        id: "SWDV",
        name: "Seawoods",
        arrivalTime: "12:03",
        latitude: 19.0345,
        longitude: 73.0185,
      },
      {
        id: "BEPR",
        name: "Belapur CBD",
        arrivalTime: "12:07",
        latitude: 19.021,
        longitude: 73.0375,
      },
      {
        id: "BMDR",
        name: "Bamandongri",
        arrivalTime: "12:15",
        latitude: 18.975,
        longitude: 73.078,
      },
      {
        id: "KRDI",
        name: "Kharkopar",
        arrivalTime: "12:18",
        latitude: 18.955,
        longitude: 73.09,
      },
      {
        id: "GVN",
        name: "Gavan",
        arrivalTime: "12:22",
        latitude: 18.932,
        longitude: 73.098,
      },
      {
        id: "RNJD",
        name: "Ranjanpada",
        arrivalTime: "12:26",
        latitude: 18.91,
        longitude: 73.105,
      },
      {
        id: "NHV",
        name: "Nhava Sheva",
        arrivalTime: "12:30",
        latitude: 18.889,
        longitude: 73.108,
      },
      {
        id: "DRNI",
        name: "Dronagiri",
        arrivalTime: "12:34",
        latitude: 18.87,
        longitude: 73.11,
      },
      {
        id: "URAN",
        name: "Uran",
        arrivalTime: "12:38",
        latitude: 18.8575,
        longitude: 73.115,
      },
    ],
  },
];

export const MOCK_ROUTES: Record<string, Station[]> = {
  "WR-F-01": MOCK_TRAINS[0].schedule,
  "WR-S-01": MOCK_TRAINS[1].schedule,
  "CR-S-01": MOCK_TRAINS[2].schedule,
  "HR-S-02": MOCK_TRAINS[3].schedule,
  "TH-S-01": MOCK_TRAINS[4].schedule,
  "UL-S-01": MOCK_TRAINS[5].schedule,
};
